### PR TITLE
Added Euler 15.

### PR DESCRIPTION
**Pull request by veddox**
In case you're interested :-)

### CODE REVIEW

**Comment by MiningMarsh** [comment]
Interesting solution, thanks for sharing!

**Comment by veddox** [comment]
You're welcome :-)

Took me three days to figure it out - first day I got absolutely nowhere, second day I settled on the DAG approach, third day I tried (and managed) to optimize if from an exponential runtime to linear...

**Comment by MiningMarsh** [comment]
Out of interest, why did you choose to contribute to this obscure little repo, vs the other project Euler repos? :)

**Comment by veddox** [comment]
short answer: it's the first one I found ;-)
long answer: I'm just getting the hang of Github and was browsing around for Common Lisp projects (since I'm currently honing my CL skills). Your repo popped up as one that was recently active, and since I have been doing Project Euler tasks in Lisp, I decided to contribute a solution...

**Pull request merged**
